<a href="https://colab.research.google.com/github/TWentCEO/GAN/blob/main/FullyConnectedLayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
class FullyConnectedLayer(object):
    def __init__(self, num_inputs, layer_size, activation_fn):
        super().__init__()
        #임의로로 매개변수를를 초기화화 (정규 분포를 사용)
        self.W = np.random.standard_normal((num_inputs, layer_size))
        self.b = np.random.standard_normal(layer_size)
        self.size = layer_size
        self.activation_fn = activation_fn

    def forward(self, x):
        z = np.dot(x, self.W) + self.b
        return self.activation_fn(z)

In [6]:
np.random.seed(42)
x1 = np.random.uniform(-1,1,2).reshape(1,2)
x2 = np.random.uniform(-1,1,2).reshape(1,2)

relu_fn = lambda y: np.maximum(y, 0) 
layer = FullyConnectedLayer(2,3,relu_fn)

In [7]:
out1 = layer.forward(x1)
out2 = layer.forward(x1)
x12 = np.concatenate((x1,x2))
out12 = layer.forward(x12)

In [8]:
print(out1)
print(out2)
print(x12)
print(out12)

[[0.28712364 0.         0.33478571]]
[[0.28712364 0.         0.33478571]]
[[-0.25091976  0.90142861]
 [ 0.46398788  0.19731697]]
[[0.28712364 0.         0.33478571]
 [0.         0.         1.08175419]]
